services:
  proxy:
    image: ghcr.io/wzshiming/socks5/socks5:v0.4.3
    ports:
      - "1080:1080"
    links:
      - ping-pong-server
  ping-pong-server:
    image: node:21
    volumes:
      - ./tests/ping-pong-server:/server
    command: sh -c "cd /server && node server.js"
