name: Static

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  psalm:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          ini-values: error_reporting=E_ALL
          coverage: none

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run psalm
        run: ./vendor/bin/psalm
